import multiprocessing

# general
CONFIG_NUM_RUNS = 1
CONFIG_SEED = 1593803615
CONFIG_NUM_CLASSES = 2

CONFIG_ISRI_DATASET_DIR = 'datasets/isri-ocr'
CONFIG_CDIP_DATASET_DIR = 'datasets/cdip'

# samples generation
CONFIG_SAMPLES_BASE_DIR = '~/samples/deeprec-icpr20' # <=  adjust dir
# CONFIG_SAMPLES_SIZE = 31 # ****************
CONFIG_SAMPLES_SIZE = 32 # new attempt
CONFIG_SAMPLES_RATIO_VAL = .1
CONFIG_SAMPLES_THRESH_BLACK = .2
CONFIG_SAMPLES_DISP_NOISE = 2
CONFIG_SAMPLES_MAX_POS = 1000
CONFIG_SAMPLES_MAX_POS_FT = 1500 # fine tuning
CONFIG_SAMPLES_RATIO_NEG = 1.0
CONFIG_SAMPLES_NUM_STRIPS = 30
CONFIG_SAMPLES_STRIDE = 2
CONFIG_SAMPLES_STRIDE_FT = 3
CONFIG_SAMPLES_STD_NOISE = 0.1

# TRAIN
CONFIG_TRAIN_BASE_DIR = '/mnt/data/traindata/deeprec-icpr20' # <=  adjust dir
# CONFIG_TRAIN_NUM_PROC = 1 # for dataset processing
CONFIG_TRAIN_NUM_PROC = max(1, multiprocessing.cpu_count() - 1) # for dataset processing
CONFIG_TRAIN_INIT_LEARNING_RATE = .0001
# CONFIG_TRAIN_BATCH_SIZE = 128 # **********
# CONFIG_TRAIN_NUM_EPOCHS = 5 # **********
CONFIG_TRAIN_BATCH_SIZE = 256 # new experiment
CONFIG_TRAIN_NUM_EPOCHS = 10 # new experiment
CONFIG_TRAIN_STEP_SIZE = .33
CONFIG_TRAIN_REPRESENTATION = 'raw'
CONFIG_TRAIN_REPRESENTATION_FT = 'grayscale'

# TEST
CONFIG_TEST_REPRESENTATION = 'binary'
CONFIG_TEST_REPRESENTATION_FT = 'grayscale'